server:
  host: localhost
  port: 3000
  cors:
    - "http://0.0.0.0:4200"
    - "http://127.0.0.1:4200"
    - "http://localhost:4200"
swagger_people:
    title: VideoGamesDotCom People
    description: Api of the people subscribe to the website
    version: 1.0
    tag: people
    path: documentation/people
swagger_games:
    title: VideoGamesDotCom Games
    description: Api of the games in the website
    version: 1.0
    tag: games
    path: documentation/games
mongodb:
  uri: mongodb://localhost:27017/vgdc